r:main.c
	gcc -o r -g main.c `/stone/local/mysql/bin/mysql_config --libs_r` `/stone/local/mysql/bin/mysql_config --include`
m:m.c
	gcc -o m -g m.c `/stone/local/mysql/bin/mysql_config --libs_r` `/stone/local/mysql/bin/mysql_config --include`

